# all Products
GET http://localhost:3001/api/products

# tag routes

###
# get all tags
GET http://localhost:3001/api/tags


###
# get tag by id 

GET http://localhost:3001/api/tags/1

###
# create new tag

POST http://localhost:3001/api/tags/
Content-Type: application/json

{
    "id":1,
    "tagName":"testTag"
}
